version: '3.8'

services:
  database:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  foodgram_web:
    image: anton1986lukin/foodgram_web:v1.0
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - database
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:  # ???
      - foodgram_web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  data:
  static_value:
  media_value:
